### ISSUE TITLE
Finders

### ISSUE THREAD

**Issue by somebody32** [therubymug/keymaker#3]
Hi

According to finders realisation: what is the best way to start from? Cypher query or rest call to index search? Have you thought about it?

**Comment by therubymug** [comment]
Sorry about the delayed response. I'm looking into integrating this gem: https://github.com/andreasronge/neo4j-cypher into Keymaker. I want to stay close to what most people are used to with ActiveRecord. e.g. User.where(name: "Morpheus") would, in the background create the proper Cypher query for you using the neo4j-cypher gem. Make sense?

**Comment by therubymug** [comment]
I added rudimentary find_by_cypher and find_all_by_cypher methods. They're on master now. Play around with them and let me know what you think. I'm planning on tackling more robust finders next! :-)
